name:                tim
version:             0.1.0
github:              "jeapostrophe/tim"
license:             Apache-2.0
author:              "Jay McCarthy"
maintainer:          "jay.mccarthy@gmail.com"
copyright:           "2020 Jay McCarthy"
description:         Efficient command-line clocking

dependencies:
- base >= 4.7 && < 5
- mtl
- time

default-extensions:
- BangPatterns
- DeriveAnyClass
- DeriveDataTypeable
- DeriveGeneric
- DerivingStrategies
- EmptyDataDeriving
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- NumericUnderscores
- OverloadedStrings
- PartialTypeSignatures
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StrictData
- TemplateHaskell
- TypeApplications
- TypeSynonymInstances

ghc-options:
- -Wall
- -Werror
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints
- -Wmissing-export-lists
- -Wpartial-fields
- -Wwarn=unused-top-binds
- -Wmonomorphism-restriction
- -O2
- -fwrite-ide-info
- -hiedir=.hie

library:
    source-dirs: src

executables:
  tim:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tim

  convert:
    main:                Main.hs
    source-dirs:        convert
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
        - tim
        - orgmode
        - megaparsec
        - containers
    